distributed.nanny - INFO -         Start Nanny at: 'tcp://10.10.15.22:39878'
distributed.worker - INFO -       Start worker at:    tcp://10.10.15.22:34309
distributed.worker - INFO -          Listening to:    tcp://10.10.15.22:34309
distributed.worker - INFO -          dashboard at:          10.10.15.22:46054
distributed.worker - INFO - Waiting to connect to:     tcp://10.10.18.8:35776
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    2.00 GB
distributed.worker - INFO -       Local Directory: /users/k1201869/wang_model/code/model_fitting/dask-worker-space/dask-worker-space/worker-s6n_xi4w
distributed.worker - INFO - -------------------------------------------------
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59720 remote=tcp://10.10.18.8:35776>
distributed.worker - INFO - Waiting to connect to:     tcp://10.10.18.8:35776
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59742 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59746 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59752 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59756 remote=tcp://10.10.18.8:35776>
distributed.worker - INFO - Waiting to connect to:     tcp://10.10.18.8:35776
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59784 remote=tcp://10.10.18.8:35776>
distributed.worker - INFO - Waiting to connect to:     tcp://10.10.18.8:35776
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59788 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59794 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59806 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59810 remote=tcp://10.10.18.8:35776>
distributed.worker - INFO - Waiting to connect to:     tcp://10.10.18.8:35776
distributed.worker - INFO - Waiting to connect to:     tcp://10.10.18.8:35776
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59854 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59858 remote=tcp://10.10.18.8:35776>
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://10.10.15.22:59860 remote=tcp://10.10.18.8:35776>
distributed.nanny - INFO - Closing Nanny at 'tcp://10.10.15.22:39878'
distributed.worker - INFO - Stopping worker at tcp://10.10.15.22:34309
distributed.worker - INFO - Closed worker has not yet started: Status.undefined
distributed.dask_worker - INFO - End worker
Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 295, in _
    await asyncio.wait_for(self.start(), timeout=timeout)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 460, in <module>
    go()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 456, in go
    main()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 442, in main
    loop.run_sync(run)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 436, in run
    await asyncio.gather(*nannies)
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/users/k1201869/miniconda3/envs/python38/lib/python3.8/site-packages/distributed/core.py", line 299, in _
    raise TimeoutError(
asyncio.exceptions.TimeoutError: Nanny failed to start in 60 seconds
